name: snowflake_dbt_orchestrated_pipeline
version: 1.0.0
config-version: 2
profile: snowflake_dbt_orchestrated_pipeline

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages", "logs"]

models:
  snowflake_dbt_orchestrated_pipeline:
    staging:
      +schema: STAGING
      +materialized: view
    marts:
      +schema: MARTS
